/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-05-27 00:13:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.prompt.gp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.ArrayList;
import java.util.List;
import jp.co.freedom.promptreport.gp.mesago.BwjGeneralPurposePromptReportResult;
import jp.co.freedom.promptreport.util.Utilities;
import java.text.NumberFormat;

public final class bwjResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// パラメータの取得
	String backURL = (String) request.getAttribute("backURL");
	String[] days = (String[]) request.getAttribute("days");
	@SuppressWarnings("unchecked")
	List<String> categoryList = (ArrayList<String>) request
			.getAttribute("categoryList");
	@SuppressWarnings("unchecked")
	List<BwjGeneralPurposePromptReportResult> resultList = (ArrayList<BwjGeneralPurposePromptReportResult>) request
			.getAttribute("resultList");
	@SuppressWarnings("unchecked")
	Map<String, Integer> repeatTotal = (LinkedHashMap<String, Integer>) request
			.getAttribute("repeatTotal");

	int newRegistAppTotal = (Integer) request
			.getAttribute("newRegistAppTotal");
	int newRegistPreTotal = (Integer) request
			.getAttribute("newRegistPreTotal");
	int repeatTotalTotal = (Integer) request
			.getAttribute("repeatTotalTotal");

	NumberFormat nfNum = NumberFormat.getNumberInstance();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>集計結果</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html,body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("} /*高さ100%に指定*/\r\n");
      out.write(".centerMiddle {\r\n");
      out.write("\tmargin: -200px 0 0 -300px; /*縦横の半分をネガティブマージンでずらす*/\r\n");
      out.write("\tposition: absolute; /*body要素に対して絶対配置*/\r\n");
      out.write("\ttop: 30%; /*上端を中央に*/\r\n");
      out.write("\tleft: 50%; /*左端を中央に*/\r\n");
      out.write("\twidth: 600px; /*横幅*/\r\n");
      out.write("\theight: 400px; /*縦幅*/\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mytable {\r\n");
      out.write("\twidth: 700px;\r\n");
      out.write("\tmargin: 0 0 0 1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-spacing: 0;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("caption {\r\n");
      out.write("\tpadding: 0 0 5px 0;\r\n");
      out.write("\tfont: italic 11px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tfont: bold 11px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #4f6b72;\r\n");
      out.write("\tborder: 1px solid #c1dad7;\r\n");
      out.write("\tletter-spacing: 2px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding: 6px 6px 6px 12px;\r\n");
      out.write("\tbackground: #cae8ea url(\"img/css/bg_header.jpg\") no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.nobg {\r\n");
      out.write("\tborder-top: 0;\r\n");
      out.write("\tborder-left: 0;\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder: 1px solid #c1dad7;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tpadding: 6px 6px 6px 12px;\r\n");
      out.write("\tcolor: #4f6b72;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.alt {\r\n");
      out.write("\tbackground: #F5FAFA;\r\n");
      out.write("\tcolor: #797268;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.spec {\r\n");
      out.write("\tbackground: #fff url(\"img/css/bullet1.gif\") no-repeat;\r\n");
      out.write("\tfont: bold 10px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.specalt {\r\n");
      out.write("\tbackground: #f5fafa url(\"img/css/bullet2.gif\") no-repeat;\r\n");
      out.write("\tfont: bold 10px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #797268;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<table id=\"mytable\" style=\"BACKGROUND-COLOR: #a9a9a9\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th rowspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">5月13日</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\">5月14日</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\">5月15日</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"3\">合計</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">新規登録数</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">新規登録数</th>\r\n");
      out.write("\t\t\t\t<th rowspan=\"2\">リピータ－</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">新規登録数</th>\r\n");
      out.write("\t\t\t\t<th rowspan=\"2\">リピータ－</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">新規登録数</th>\r\n");
      out.write("\t\t\t\t<th rowspan=\"2\">リピータ－</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>業種</th>\r\n");
      out.write("\t\t\t\t<th>当日</th>\r\n");
      out.write("\t\t\t\t<th>事前</th>\r\n");
      out.write("\t\t\t\t<th>当日</th>\r\n");
      out.write("\t\t\t\t<th>事前</th>\r\n");
      out.write("\t\t\t\t<th>当日</th>\r\n");
      out.write("\t\t\t\t<th>事前</th>\r\n");
      out.write("\t\t\t\t<th>当日</th>\r\n");
      out.write("\t\t\t\t<th>事前</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				//1日目
				List<Map.Entry<String, Integer>> newRegistAppList1 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(0).newRegistApp.entrySet());
				List<Map.Entry<String, Integer>> newRegistPreList1 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(0).newRegistPre.entrySet());
				List<Map.Entry<String, Integer>> repeatList1 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(0).repeat.entrySet());
				//2日目
				List<Map.Entry<String, Integer>> newRegistAppList2 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(1).newRegistApp.entrySet());
				List<Map.Entry<String, Integer>> newRegistPreList2 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(1).newRegistPre.entrySet());
				List<Map.Entry<String, Integer>> repeatList2 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(1).repeat.entrySet());
				//3日目
				List<Map.Entry<String, Integer>> newRegistAppList3 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(2).newRegistApp.entrySet());
				List<Map.Entry<String, Integer>> newRegistPreList3 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(2).newRegistPre.entrySet());
				List<Map.Entry<String, Integer>> repeatList3 = new ArrayList<Map.Entry<String, Integer>>(
						resultList.get(2).repeat.entrySet());
				//リピーター合計
				List<Map.Entry<String, Integer>> repeatTotalList = new ArrayList<Map.Entry<String, Integer>>(
						repeatTotal.entrySet());
			
      out.write("\r\n");
      out.write("\t\t\t");

				for (int nCategory = 0; nCategory <= categoryList.size(); nCategory++) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- 1日目 -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"left\">");
      out.print(nCategory != categoryList.size() ? categoryList
						.get(nCategory) : "2013年度来場者");
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistAppList1.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistPreList1.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 2日目 -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistAppList2.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistPreList2.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(repeatList2.get(nCategory).getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 3日目 -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistAppList3.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistPreList3.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(repeatList3.get(nCategory).getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 合計 -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistAppList1.get(nCategory)
						.getValue()
						+ newRegistAppList2.get(nCategory).getValue()
						+ newRegistAppList3.get(nCategory).getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistPreList1.get(nCategory)
						.getValue()
						+ newRegistPreList2.get(nCategory).getValue()
						+ newRegistPreList3.get(nCategory).getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(repeatTotalList.get(nCategory)
						.getValue()));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">合計</td>\r\n");
      out.write("\t\t\t\t");

					for (int nDay = 0; nDay < days.length; nDay++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(Utilities.sum(resultList.get(nDay).newRegistApp)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(Utilities.sum(resultList.get(nDay).newRegistPre)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

					if (nDay != 0) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(Utilities.sum(resultList.get(nDay).repeat)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 合計 -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistAppTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(newRegistPreTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(repeatTotalTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br /> <br /> <a href=\"");
      out.print(backURL);
      out.write("\">もどる</a> <br /> <br />\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
