/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-05-08 08:14:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.prompt.gp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import jp.co.freedom.promptreport.gp.mesago.BwjGateAnalyzeResult;
import jp.co.freedom.promptreport.gp.mesago.BwjGateAnalyzeTotalResult;
import java.text.NumberFormat;

public final class gateTimeAnalyze_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// パラメータの取得
	String caption = (String) request.getAttribute("caption");
	@SuppressWarnings("unchecked")
	List<BwjGateAnalyzeResult[]> resultList = (ArrayList<BwjGateAnalyzeResult[]>) request
			.getAttribute("resultList");
	@SuppressWarnings("unchecked")
	List<String> categoryList = (ArrayList<String>) request
			.getAttribute("categoryList");
	@SuppressWarnings("unchecked")
	List<BwjGateAnalyzeTotalResult> totalList = (ArrayList<BwjGateAnalyzeTotalResult>) request
			.getAttribute("totalList");
	NumberFormat nfNum = NumberFormat.getNumberInstance();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>集計結果</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#mytable {\r\n");
      out.write("\twidth: 700px;\r\n");
      out.write("\tmargin: 0 0 0 1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-spacing: 0;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("caption {\r\n");
      out.write("\tpadding: 0 0 5px 0;\r\n");
      out.write("\tfont: italic 11px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tfont: bold 11px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #4f6b72;\r\n");
      out.write("\tborder: 1px solid #c1dad7;\r\n");
      out.write("\tletter-spacing: 2px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding: 6px 6px 6px 12px;\r\n");
      out.write("\tbackground: #cae8ea url(\"img/css/bg_header.jpg\") no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.nobg {\r\n");
      out.write("\tborder-top: 0;\r\n");
      out.write("\tborder-left: 0;\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder: 1px solid #c1dad7;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tpadding: 6px 6px 6px 12px;\r\n");
      out.write("\tcolor: #4f6b72;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.alt {\r\n");
      out.write("\tbackground: #F5FAFA;\r\n");
      out.write("\tcolor: #797268;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.spec {\r\n");
      out.write("\tbackground: #fff url(\"img/css/bullet1.gif\") no-repeat;\r\n");
      out.write("\tfont: bold 10px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.specalt {\r\n");
      out.write("\tbackground: #f5fafa url(\"img/css/bullet2.gif\") no-repeat;\r\n");
      out.write("\tfont: bold 10px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #797268;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<div>東3ホール</div>\r\n");
      out.write("\t\t<table id=\"mytable\" style=\"BACKGROUND-COLOR: #a9a9a9\">\r\n");
      out.write("\t\t\t<caption>");
      out.print(caption);
      out.write("</caption>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t<th colspan=\"4\">第3ホール</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"4\">第4ホール</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"4\">第5ホール</th>\r\n");
      out.write("\t\t\t\t<th colspan=\"4\">第6ホール</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t");

					for (int nIndex = 1; nIndex <= 4; nIndex++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<th>当日登録</th>\r\n");
      out.write("\t\t\t\t<th>事前登録</th>\r\n");
      out.write("\t\t\t\t<th>リピーター</th>\r\n");
      out.write("\t\t\t\t<th>合計</th>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				for (int nIndex = 1; nIndex <= resultList.size(); nIndex++) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(resultList.get(nIndex - 1)[0].endTime - 1);
      out.write(":00～");
      out.print(resultList.get(nIndex - 1)[0].endTime);
      out.write(":00</td>\r\n");
      out.write("\t\t\t\t<!-- 東3ホール  -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[0].appointedday));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[0].preentry));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[0].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[0].appointedday
						+ resultList.get(nIndex - 1)[0].preentry
						+ resultList.get(nIndex - 1)[0].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 東4ホール  -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[1].appointedday));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[1].preentry));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[1].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[1].appointedday
						+ resultList.get(nIndex - 1)[1].preentry
						+ resultList.get(nIndex - 1)[1].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 東5ホール  -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[2].appointedday));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[2].preentry));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[2].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[2].appointedday
						+ resultList.get(nIndex - 1)[2].preentry
						+ resultList.get(nIndex - 1)[2].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 東6ホール  -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[3].appointedday));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[3].preentry));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[3].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(resultList.get(nIndex - 1)[3].appointedday
						+ resultList.get(nIndex - 1)[3].preentry
						+ resultList.get(nIndex - 1)[3].repeat));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">合計</td>\r\n");
      out.write("\t\t\t\t");

					for (int nIndex = 0; nIndex < totalList.size(); nIndex++) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 東3ホール  -->\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(totalList.get(nIndex).appointeddayTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(totalList.get(nIndex).preentryTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(totalList.get(nIndex).repeatTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"alt\" align=\"right\">");
      out.print(nfNum.format(totalList.get(nIndex).totalTotal));
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<p />\r\n");
      out.write("\r\n");
      out.write("\t\t<br /> <br /> <a\r\n");
      out.write("\t\t\thref=\"html/prompt/bwjGeneralPurposePromptReport.html\">もどる</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
