/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-09-04 00:05:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.jsp.prompt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dbOperation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      out.write('\r');
      out.write('\n');

// パラメータの取得
String backURL = (String) request.getAttribute( "backURL" );
String result = (String) request.getAttribute( "result" );


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>CSVアップロード完了</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\thtml, body {\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t}/*高さ100%に指定*/\r\n");
      out.write("\t\t\t.centerMiddle {\r\n");
      out.write("\t\t\t\tmargin: -200px 0 0 -300px; /*縦横の半分をネガティブマージンでずらす*/\r\n");
      out.write("\t\t\t\tposition: absolute; /*body要素に対して絶対配置*/\r\n");
      out.write("\t\t\t\ttop: 50%; /*上端を中央に*/\r\n");
      out.write("\t\t\t\tleft: 50%; /*左端を中央に*/\r\n");
      out.write("\t\t\t\twidth: 600px; /*横幅*/\r\n");
      out.write("\t\t\t\theight: 400px; /*縦幅*/\r\n");
      out.write("\t\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#mytable {\r\n");
      out.write("\t\t\t\twidth: 700px;\r\n");
      out.write("\t\t\t\tmargin: 0 0 0 1px;\r\n");
      out.write("\t\t\t\tpadding: 0;\r\n");
      out.write("\t\t\t\tborder: 0;\r\n");
      out.write("\t\t\t\tborder-spacing: 0;\r\n");
      out.write("\t\t\t\tborder-collapse: collapse;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcaption {\r\n");
      out.write("\t\t\t\tpadding: 0 0 5px 0;\r\n");
      out.write("\t\t\t\tfont: italic 11px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\t\t\t\ttext-align: right;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tth {\r\n");
      out.write("\t\t\t\tfont: bold 11px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\t\t\t\tcolor: #4f6b72;\r\n");
      out.write("\t\t\t\tborder: 1px solid #c1dad7;\r\n");
      out.write("\t\t\t\tletter-spacing: 2px;\r\n");
      out.write("\t\t\t\ttext-transform: uppercase;\r\n");
      out.write("\t\t\t\ttext-align: left;\r\n");
      out.write("\t\t\t\tpadding: 6px 6px 6px 12px;\r\n");
      out.write("\t\t\t\tbackground: #cae8ea url(\"img/css/bg_header.jpg\") no-repeat;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tth.nobg {\r\n");
      out.write("\t\t\t\tborder-top: 0;\r\n");
      out.write("\t\t\t\tborder-left: 0;\r\n");
      out.write("\t\t\t\tbackground: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttd {\r\n");
      out.write("\t\t\t\tborder: 1px solid #c1dad7;\r\n");
      out.write("\t\t\t\tbackground: #fff;\r\n");
      out.write("\t\t\t\tpadding: 6px 6px 6px 12px;\r\n");
      out.write("\t\t\t\tcolor: #4f6b72;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttd.alt {\r\n");
      out.write("\t\t\t\tbackground: #F5FAFA;\r\n");
      out.write("\t\t\t\tcolor: #797268;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tth.spec {\r\n");
      out.write("\t\t\t\tbackground: #fff url(\"img/css/bullet1.gif\") no-repeat;\r\n");
      out.write("\t\t\t\tfont: bold 10px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tth.specalt {\r\n");
      out.write("\t\t\t\tbackground: #f5fafa url(\"img/css/bullet2.gif\") no-repeat;\r\n");
      out.write("\t\t\t\tfont: bold 10px \"Trebuchet MS\", Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\t\t\t\tcolor: #797268;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"centerMiddle\">\r\n");
      out.write("\t\t\t<table id=\"mytable\">\r\n");
      out.write("\t\t\t\t<caption>速報集計</caption>\r\n");
      out.write("\t\t\t\t<tr height=\"300\">\r\n");
      out.write("\t\t\t\t\t<td class=\"alt\" width=\"300\" align=\"center\">");
      out.print( result );
      out.write("<br/><br/><a href=\"");
      out.print( backURL );
      out.write("\">もどる</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
